en:
  languageName: English
  weight: 1
  params:
    title: "DeepCausality"
    description: "Computational causality for Rust"

    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/accessibility/"

    ### calls to action ###
    main_cta:
      text: "GitHub"
      link: "https://github.com/deepcausality-rs/deep_causality"

    footer_cta:
      text: "GitHub"
      link: "https://github.com/deepcausality-rs/deep_causality"

    ### copyright (markdown can be used) ###
    copyright: "Copyright &copy; {{< current_year >}} DeepCausality. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
    github_edit: "Edit this page on GitHub"

  ### menu ###
  menu:
    main:
    - identifier: "about"
      post: "About DeepCausality"
      name: "About"
      url: "/about/"
      weight: 1

    - identifier: "getting-started"
      name: "Getting Started"
      url: "/getting-started/"
      weight: 2

    - identifier: "docs"
      name: "Docs"
      url: "/docs/"
      weight: 3

    - identifier: "context"
      name: "Context"
      url: "/docs/context/"
      weight: 1
      parent: "docs"

    - identifier: "causal-structure"
      name: "Causal Data Structure"
      url: "/docs/causal-structure/"
      weight: 2
      parent: "docs"

    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3

    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 4
