baseURL = '/'
theme = "LoveIt"
title = "DeepCausality"

languageCode = "en-us"
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false

# Author config
[author]
name = "Marvin Hansen"
email = "marvin.hansen@gmail.com"
link = ""

# default amount of posts in each pages
paginate = 12
# google analytics code [UA-XXXXXXXX-X]
googleAnalytics = ""
# copyright description used only for seo schema
copyright = "(C) DeepCausality"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true


[params]
# site default theme ["auto", "light", "dark"]
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
gitRepo = "https://github.com/deepcausality-rs/deep_causality"
# LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = "sha512"
# LoveIt NEW | 0.2.0 date format
dateFormat = "2006-01-02"
# website title for Open Graph and Twitter Cards
title = "DeepCausality"
# website description for RSS, SEO, Open Graph and Twitter Cards
description = ""
# website images for Open Graph and Twitter Cards
#images = ["/logo.png"]

# Menu config
[menu]

[[menu.main]]
weight = 1
identifier = "about"
pre = ""
post = ""
name = "About"
url = "/about/"
title = ""


[[menu.main]]
weight = 2
identifier = "posts"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Blog"
url = "/posts/"
# title will be shown when you hover on this menu link
title = "Blog posts"


# Markup related configuration in Hugo
[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

# Footer config
[params.footer]
enable = true
# LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
custom = ''
# LoveIt NEW | 0.2.0 whether to show Hugo and theme info
hugo = false
# LoveIt NEW | 0.2.0 whether to show copyright info
copyright = true
# LoveIt NEW | 0.2.0 whether to show the author
author = true
# Site creation time
since = 2022
# ICP info only in China (HTML format is supported)
icp = ""
# license info (HTML format is supported)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
